# This will appear before many messages from the plugin.
message-prefix: '&9[&3ParticleEffects&9]'

# Use a minecraft colour code here to pick the message colour
message-colour: '3'

# The highlight colour (to complement the above colour)
highlight-colour: 'b'

# Errors will be this colour.
error-colour: 'c'

# Error highlights
error-highlight: '7'